# Generated by Django 5.1.15 on 2026-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='plan_preference',
            field=models.CharField(blank=True, choices=[('subscription', 'Subscription Only'), ('purchase', 'Purchase Only'), ('both', 'Subscription + Purchase')], help_text="User's preferred plan type from onboarding", max_length=20, null=True),
        ),
    ]
