# Generated by Django 5.1.15 on 2026-01-23 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_parentprofile_plan_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, choices=[('PRE_K', 'Pre-K'), ('KINDERGARTEN', 'Kindergarten'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='reading_difficulty_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner (Ages 3-6)'), ('INTERMEDIATE', 'Intermediate (Ages 7-10)'), ('ADVANCED', 'Advanced (Ages 11-14)')], help_text='Reading difficulty level for book curation', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
