# Generated by Django 5.1.15 on 2026-01-23 05:25

from django.db import migrations, models


def set_existing_profiles_as_completed(apps, schema_editor):
    """Set onboarding_completed=True for all existing ParentProfiles"""
    ParentProfile = apps.get_model('profiles', 'ParentProfile')
    ParentProfile.objects.all().update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_child_age_alter_child_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the full onboarding process'),
        ),
        migrations.RunPython(set_existing_profiles_as_completed, reverse_code=migrations.RunPython.noop),
    ]
