# Generated by Django 5.1.15 on 2026-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_parentprofile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='interests',
            field=models.TextField(blank=True, help_text="Child's interests for book curation", null=True),
        ),
    ]
