# Generated by Django 5.1.15 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_child_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='interests',
        ),
        migrations.AddField(
            model_name='child',
            name='reading_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy percentage from fluency check', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='reading_test_completed',
            field=models.BooleanField(default=False, help_text='Whether the child has completed their first reading test'),
        ),
        migrations.AddField(
            model_name='child',
            name='reading_wpm',
            field=models.IntegerField(blank=True, help_text='Words per minute from fluency check', null=True),
        ),
    ]
