# Generated by Django 5.1.15 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_child_interests_child_reading_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='interests',
            field=models.TextField(blank=True, help_text="Child's interests (e.g., animals, space, adventures)", null=True),
        ),
    ]
