# Generated by Django 5.1.15 on 2026-02-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_child_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='reading_gaps',
            field=models.TextField(blank=True, help_text='Areas for improvement identified in reading', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='reading_strengths',
            field=models.TextField(blank=True, help_text='Strengths identified in reading', null=True),
        ),
    ]
