# Generated by Django 5.1.15 on 2026-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_child_reading_gaps_child_reading_strengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Whether this child's profile is currently active"),
        ),
    ]
