# Generated by Django 5.1.15 on 2026-02-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_child_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='has_tried_other_languages',
            field=models.BooleanField(default=False, help_text='Whether the child has tried or dismissed the multilingual banner'),
        ),
    ]
