# Generated by Django 5.1.15 on 2026-02-24 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_seed_reading_passages'),
        ('profiles', '0010_child_has_tried_other_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfileExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, choices=[('ENGLISH', 'English Medium'), ('HINDI', 'Hindi Medium'), ('KANNADA', 'Kannada Medium'), ('MARATHI', 'Marathi Medium'), ('TAMIL', 'Tamil Medium'), ('TELUGU', 'Telugu Medium'), ('BENGALI', 'Bengali Medium'), ('GUJARATI', 'Gujarati Medium'), ('PUNJABI', 'Punjabi Medium'), ('OTHER', 'Other')], help_text='Language of instruction at school', max_length=20, null=True)),
                ('primary_language', models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('HINDI', 'Hindi'), ('KANNADA', 'Kannada'), ('MARATHI', 'Marathi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('BENGALI', 'Bengali'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('OTHER', 'Other')], help_text="Child's primary reading/home language", max_length=20, null=True)),
                ('other_languages', models.CharField(blank=True, help_text='Other languages the child knows (comma-separated)', max_length=200, null=True)),
                ('comprehension_level', models.CharField(blank=True, choices=[('BASIC', 'Basic – understands simple sentences'), ('DEVELOPING', 'Developing – follows short stories'), ('PROFICIENT', 'Proficient – understands complex texts'), ('ADVANCED', 'Advanced – critical comprehension')], max_length=20, null=True)),
                ('reads_aloud', models.BooleanField(default=False, help_text='Child typically reads aloud rather than silently')),
                ('skips_words', models.BooleanField(default=False, help_text='Child tends to skip unfamiliar words')),
                ('reading_speed_perception', models.CharField(blank=True, choices=[('SLOW', 'Slow – reads carefully, word by word'), ('AVERAGE', 'Average – normal pace'), ('FAST', 'Fast – reads quickly'), ('VARIES', 'Varies – depends on material')], help_text="Parent's perception of child's reading speed", max_length=10, null=True)),
                ('avg_screen_time_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Average daily screen time in hours', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_profile', to='profiles.child')),
            ],
            options={
                'verbose_name': 'Child Profile Extra',
                'verbose_name_plural': 'Child Profile Extras',
            },
        ),
        migrations.CreateModel(
            name='ParentProfileExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('SEVERAL_WEEK', 'Several times a week'), ('ONCE_WEEK', 'Once a week'), ('RARELY', 'Rarely'), ('NEVER', 'Never')], help_text='How often parent reads with child', max_length=20, null=True)),
                ('provides_assistance', models.BooleanField(default=False, help_text='Parent actively assists child during reading sessions')),
                ('books_at_home', models.PositiveIntegerField(blank=True, help_text='Approximate number of books at home', null=True, validators=[django.core.validators.MaxValueValidator(500)])),
                ('preferred_reading_time', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('BEDTIME', 'Bedtime'), ('WEEKEND', 'Weekends only')], max_length=20, null=True)),
                ('reading_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Typical reading session duration in minutes', null=True, validators=[django.core.validators.MaxValueValidator(180)])),
                ('profile_completed', models.BooleanField(default=False, help_text='Whether the parent has completed the enhanced profile form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_profile', to='profiles.parentprofile')),
            ],
            options={
                'verbose_name': 'Parent Profile Extra',
                'verbose_name_plural': 'Parent Profile Extras',
            },
        ),
        migrations.CreateModel(
            name='ReadingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField(help_text='Words per minute', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('accuracy', models.FloatField(help_text='Accuracy percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner (Ages 3-6)'), ('INTERMEDIATE', 'Intermediate (Ages 7-10)'), ('ADVANCED', 'Advanced (Ages 11-14)')], help_text='Reading level assigned at time of assessment', max_length=20)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('gaps', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('KN', 'Kannada')], default='EN', max_length=5)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_assessments', to='profiles.child')),
                ('passage', models.ForeignKey(blank=True, help_text='DB passage used (null when static passage was used)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='portal.readingpassage')),
            ],
            options={
                'verbose_name': 'Reading Assessment',
                'verbose_name_plural': 'Reading Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
