# Generated by Django 5.1.15 on 2026-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_add_profileextras_readingassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofileextra',
            name='motivation_method',
            field=models.TextField(blank=True, help_text='Comma-separated list of motivation methods (rewards, praise, routine, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='parentprofileextra',
            name='reading_companion',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BOTH', 'Both Parents'), ('GRANDPARENT', 'Grandparent'), ('SIBLING', 'Sibling'), ('TUTOR', 'Tutor'), ('SELF', 'Self-Reading')], help_text='Who typically helps the child read', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentprofileextra',
            name='reading_space',
            field=models.CharField(blank=True, choices=[('SEPARATE_ROOM', 'Separate Room'), ('SHARED_SPACE', 'Shared Space'), ('NO_FIXED', 'No Fixed Place')], help_text='Where the child usually reads', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentprofileextra',
            name='study_environment',
            field=models.CharField(blank=True, choices=[('QUIET', 'Always Quiet'), ('SOMETIMES_NOISY', 'Sometimes Noisy'), ('MOSTLY_NOISY', 'Mostly Noisy')], help_text='Quietness level of reading environment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentprofileextra',
            name='supervision_level',
            field=models.CharField(blank=True, choices=[('ALWAYS', 'Always Monitored'), ('SOMETIMES', 'Sometimes Monitored'), ('RARELY', 'Rarely Monitored')], help_text='How closely parent monitors reading', max_length=20, null=True),
        ),
    ]
