# Generated by Django 5.1.15 on 2026-02-25 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_communityprogress'),
        ('profiles', '0012_add_home_learning_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='location_consented',
            field=models.BooleanField(default=False, help_text='Whether parent has consented to include child in community progress statistics'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='address_completed',
            field=models.BooleanField(default=False, help_text='Whether the parent has completed address entry for community features'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='address_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when address was last verified', null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality/neighborhood for community progress grouping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readingassessment',
            name='improvement_percent',
            field=models.FloatField(blank=True, help_text='% change in WPM compared to previous assessment', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='readingassessment',
            index=models.Index(fields=['child', '-assessed_at'], name='profiles_re_child_i_3fbe80_idx'),
        ),
        migrations.AddIndex(
            model_name='readingassessment',
            index=models.Index(fields=['level'], name='profiles_re_level_b93741_idx'),
        ),
    ]
