# Generated by Django 5.1.15 on 2026-02-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_child_location_consented_and_more'),
    ]

    operations = [
        # Add missing columns via raw SQL (with error handling for already-existing columns)
        migrations.RunSQL(
            sql="""
            ALTER TABLE profiles_parentprofile
            ADD COLUMN IF NOT EXISTS locality varchar(100) NULL,
            ADD COLUMN IF NOT EXISTS address_completed boolean NOT NULL DEFAULT false,
            ADD COLUMN IF NOT EXISTS address_verified_at timestamp with time zone NULL;
            """,
            reverse_sql="",
            state_operations=[],
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE profiles_child
            ADD COLUMN IF NOT EXISTS location_consented boolean NOT NULL DEFAULT false;
            """,
            reverse_sql="",
            state_operations=[],
        ),
        # Note: improvement_percent and indexes were already added in 0013
    ]
