# Generated by Django 5.1.15 on 2026-02-25 12:17
# Empty migration - fields already removed in database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_add_community_progress_fields'),
    ]

    operations = [
        # Fields already removed - no operations needed
    ]
