# Generated by Django 5.1.15 on 2026-02-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_parentprofileextra_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='location_consented',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='address_completed',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='address_verified_at',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='locality',
        ),
    ]
