# Generated by Django 5.1.15 on 2026-03-02 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_child_location_consented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='consecutive_low_accuracy_pages',
            field=models.IntegerField(default=0, help_text='Counter for consecutive pages below 85% accuracy threshold'),
        ),
        migrations.AddField(
            model_name='child',
            name='frustration_mode',
            field=models.BooleanField(default=False, help_text='True when child scored below 85% accuracy on 2 consecutive pages'),
        ),
        migrations.AddField(
            model_name='child',
            name='phonetic_weaknesses',
            field=models.JSONField(blank=True, default=dict, help_text='Accumulated phoneme error counts e.g. {"th": 5, "sh": 2}'),
        ),
        migrations.AddField(
            model_name='child',
            name='reading_style',
            field=models.CharField(blank=True, choices=[('GUESSR', 'Guesser – meaning-driven reading'), ('DECODER', 'Decoder – phonics-driven, slow reading')], help_text='Dominant reading strategy detected from miscue analysis', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readingassessment',
            name='decoding_latency_data',
            field=models.JSONField(blank=True, help_text='Inter-word pause durations e.g. [{"word": "cat", "pause_before": 2.1}]', null=True),
        ),
        migrations.AddField(
            model_name='readingassessment',
            name='miscue_data',
            field=models.JSONField(blank=True, help_text='Miscue error breakdown e.g. {"nonsense": 3, "semantic": 5, "visual": 2}', null=True),
        ),
        migrations.AddField(
            model_name='readingassessment',
            name='phoneme_accuracy',
            field=models.FloatField(blank=True, help_text='Phoneme-level match rate (0–100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('KN', 'Kannada')], default='EN', max_length=5)),
                ('difficulty', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner (Ages 3-6)'), ('INTERMEDIATE', 'Intermediate (Ages 7-10)'), ('ADVANCED', 'Advanced (Ages 11-14)')], help_text='Approximate difficulty level of this word', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vocabulary Word',
                'verbose_name_plural': 'Vocabulary Words',
                'ordering': ['word'],
                'unique_together': {('word', 'language')},
            },
        ),
        migrations.AddField(
            model_name='child',
            name='vocabulary_bank',
            field=models.ManyToManyField(blank=True, help_text='Words the child has demonstrated mastery of', related_name='children', to='profiles.vocabularyword'),
        ),
    ]
