# Generated by Django 5.0.9 on 2026-01-13 03:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books_per_month', models.IntegerField(help_text='Number of books per month', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('age_group_min', models.IntegerField(help_text='Minimum age (3-14)', validators=[django.core.validators.MinValueValidator(3)])),
                ('age_group_max', models.IntegerField(help_text='Maximum age (3-14)', validators=[django.core.validators.MinValueValidator(3)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['age_group_min', 'price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.parentprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expected_return_date', models.DateField(help_text='30 days from issue date')),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost/Damaged')], default='ACTIVE', max_length=20)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, help_text='₹50/day after grace period', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycles', to='profiles.child')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cycles', to='orders.order')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycles', to='profiles.parentprofile')),
                ('physical_copies', models.ManyToManyField(help_text='Books issued in this cycle', related_name='subscription_cycles', to='inventory.physicalcopy')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='orders.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Cycle',
                'verbose_name_plural': 'Subscription Cycles',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['parent', 'status'], name='orders_orde_parent__0c1eba_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['status', '-issue_date'], name='orders_subs_status_5479d7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['child', '-issue_date'], name='orders_subs_child_i_9faa79_idx'),
        ),
    ]
