# Generated by Django 5.1.15 on 2026-01-28 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(help_text="Django model name (e.g., 'catalog.Book')", max_length=100)),
                ('items_per_page', models.PositiveIntegerField(default=10)),
                ('enable_search', models.BooleanField(default=True)),
                ('enable_sorting', models.BooleanField(default=True)),
                ('enable_pagination', models.BooleanField(default=True)),
                ('mobile_card_view', models.BooleanField(default=True)),
                ('table_class', models.CharField(default='data-table', max_length=100)),
                ('header_style', models.CharField(choices=[('gradient', 'Gradient Header'), ('solid', 'Solid Color'), ('minimal', 'Minimal')], default='gradient', max_length=20)),
                ('row_striping', models.BooleanField(default=True)),
                ('hover_effects', models.BooleanField(default=True)),
                ('compact_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Table Configuration',
                'verbose_name_plural': 'Table Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('custom', 'Custom')], default='view', max_length=20)),
                ('url_pattern', models.CharField(help_text="URL pattern, use {id} for object ID (e.g., '/admin/catalog/book/{id}/change/')", max_length=200)),
                ('button_class', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='primary', max_length=50)),
                ('icon', models.CharField(blank=True, help_text="Icon class (e.g., 'fas fa-edit')", max_length=50)),
                ('required_permission', models.CharField(blank=True, help_text='Permission required to show this action', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('table_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.tableconfiguration')),
            ],
            options={
                'verbose_name': 'Table Action',
                'verbose_name_plural': 'Table Actions',
                'ordering': ['table_config', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TableFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('text', 'Text Search'), ('select', 'Dropdown'), ('date_range', 'Date Range'), ('number_range', 'Number Range'), ('boolean', 'Yes/No'), ('multiselect', 'Multi Select')], default='text', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('choices', models.JSONField(blank=True, default=dict, help_text='JSON object with choices')),
                ('order', models.PositiveIntegerField(default=0)),
                ('table_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='core.tableconfiguration')),
            ],
            options={
                'verbose_name': 'Table Filter',
                'verbose_name_plural': 'Table Filters',
                'ordering': ['table_config', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field name (e.g., 'title', 'publisher.name')", max_length=100)),
                ('display_name', models.CharField(help_text='Header text', max_length=100)),
                ('column_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('datetime', 'Date & Time'), ('boolean', 'Boolean'), ('image', 'Image'), ('url', 'URL'), ('email', 'Email'), ('custom', 'Custom Template')], default='text', max_length=20)),
                ('width', models.CharField(blank=True, help_text="CSS width (e.g., '150px', '20%')", max_length=20)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('sortable', models.BooleanField(default=True)),
                ('searchable', models.BooleanField(default=True)),
                ('truncate', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='For truncation', null=True)),
                ('custom_template', models.TextField(blank=True, help_text='Custom Django template for rendering')),
                ('order', models.PositiveIntegerField(default=0)),
                ('table_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.tableconfiguration')),
            ],
            options={
                'verbose_name': 'Table Column',
                'verbose_name_plural': 'Table Columns',
                'ordering': ['table_config', 'order'],
                'unique_together': {('table_config', 'field_name')},
            },
        ),
    ]
