# Generated by Django 5.1.15 on 2026-01-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_status'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DELIVERY_DELAY', 'Delivery Delay'), ('MISSING_BOOK', 'Missing Book'), ('DAMAGED_BOOK', 'Damaged Book'), ('PAYMENT_ISSUE', 'Payment Issue'), ('TECHNICAL_GLITCH', 'Technical Glitch'), ('OTHER', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Optional: Reference to a specific order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.order')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='profiles.parentprofile')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
