# Generated by Django 5.1.15 on 2026-02-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='The reading passage text')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('KN', 'Kannada')], default='EN', max_length=5)),
                ('grade', models.CharField(choices=[('PRE_K', 'Pre-K'), ('KINDERGARTEN', 'Kindergarten'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8')], max_length=20)),
                ('theme', models.CharField(choices=[('adventure', 'Adventure'), ('animals', 'Animals'), ('space', 'Space'), ('fairy_tales', 'Fairy Tales')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive passages won't appear in fluency checks")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reading Passage',
                'verbose_name_plural': 'Reading Passages',
                'ordering': ['language', 'grade', 'theme', 'title'],
            },
        ),
    ]
