# Generated by Django 5.1.15 on 2026-02-17 07:22

from django.db import migrations


def seed_passages(apps, schema_editor):
    ReadingPassage = apps.get_model('portal', 'ReadingPassage')

    # Import the static passages dict
    from apps.portal.reading_passages import READING_PASSAGES

    for lang, grades in READING_PASSAGES.items():
        for grade, passages in grades.items():
            if not isinstance(passages, list):
                passages = [passages]
            for p in passages:
                ReadingPassage.objects.create(
                    title=p['title'],
                    text=p['text'],
                    word_count=p.get('word_count', len(p['text'].split())),
                    language=lang,
                    grade=grade,
                    theme=p.get('theme', 'adventure'),
                    is_active=True,
                )


def remove_passages(apps, schema_editor):
    ReadingPassage = apps.get_model('portal', 'ReadingPassage')
    ReadingPassage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_readingpassage'),
    ]

    operations = [
        migrations.RunPython(seed_passages, remove_passages),
    ]
