# Generated by Django 5.1.15 on 2026-02-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_seed_reading_passages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('locality', models.CharField(db_index=True, max_length=100)),
                ('reading_level', models.CharField(choices=[('BEGINNER', 'Beginner (Ages 3-6)'), ('INTERMEDIATE', 'Intermediate (Ages 7-10)'), ('ADVANCED', 'Advanced (Ages 11-14)')], db_index=True, max_length=20)),
                ('child_count', models.PositiveIntegerField(default=0, help_text='Number of children at this level in this location')),
                ('avg_wpm', models.FloatField(blank=True, help_text='Average words per minute', null=True)),
                ('avg_accuracy', models.FloatField(blank=True, help_text='Average accuracy percentage', null=True)),
                ('improvement_percent', models.FloatField(blank=True, help_text='Average % improvement compared to previous assessments', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community Progress',
                'verbose_name_plural': 'Community Progress',
                'ordering': ['city', 'locality', 'reading_level'],
                'indexes': [models.Index(fields=['city', 'locality'], name='portal_comm_city_28b112_idx'), models.Index(fields=['reading_level'], name='portal_comm_reading_263b6e_idx'), models.Index(fields=['-last_updated'], name='portal_comm_last_up_d980bb_idx')],
                'unique_together': {('city', 'locality', 'reading_level')},
            },
        ),
    ]
