# Generated by Django 5.1.15 on 2026-02-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_status'),
        ('profiles', '0015_remove_child_location_consented_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating')),
                ('going_well', models.JSONField(blank=True, default=list, help_text="List of choice keys for what's working well")),
                ('needs_improvement', models.JSONField(blank=True, default=list, help_text='List of choice keys for what needs improvement')),
                ('child_age_group', models.CharField(blank=True, choices=[('pre_k', 'Pre-K'), ('grade_1_2', 'Grade 1-2'), ('grade_3_4', 'Grade 3-4'), ('grade_5_plus', 'Grade 5+')], help_text='Age group of child', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Optional additional comments', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_feedbacks', to='profiles.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feedback_ap_created_a22b18_idx'), models.Index(fields=['rating'], name='feedback_ap_rating_1a9844_idx')],
            },
        ),
        migrations.CreateModel(
            name='CycleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 star rating for books')),
                ('enjoyed', models.JSONField(blank=True, default=list, help_text='List of choice keys for what went well')),
                ('needs_improvement', models.JSONField(blank=True, default=list, help_text='List of choice keys for improvements')),
                ('comments', models.TextField(blank=True, help_text='Optional additional comments', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_feedbacks', to='profiles.child')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.subscriptioncycle')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_feedbacks', to='profiles.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', '-created_at'], name='feedback_cy_parent__32b2ca_idx'), models.Index(fields=['rating'], name='feedback_cy_rating_3b921d_idx')],
            },
        ),
    ]
