# Generated by Django 5.1.15 on 2026-02-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appfeedback',
            name='child_age_group',
        ),
    ]
