# Generated by Django 5.0.9 on 2026-01-13 03:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Full response from Razorpay for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='payments_tr_created_748acf_idx'), models.Index(fields=['razorpay_order_id'], name='payments_tr_razorpa_7ef816_idx'), models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx')],
            },
        ),
    ]
