# Generated by Django 5.0.9 on 2026-01-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (card, netbanking, upi, etc.)', max_length=50),
        ),
    ]
