# Generated by Django 5.0.9 on 2026-01-13 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Unique barcode/ID for this copy', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20)),
                ('condition_notes', models.TextField(blank=True, help_text='Notes about the condition of this copy')),
                ('purchased_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_copies', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Physical Copy',
                'verbose_name_plural': 'Physical Copies',
                'ordering': ['book', 'barcode'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADDED', 'Added to Inventory'), ('ISSUED', 'Issued to Customer'), ('RETURNED', 'Returned by Customer'), ('DAMAGED', 'Marked as Damaged'), ('LOST', 'Marked as Lost'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL)),
                ('physical_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.physicalcopy')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='physicalcopy',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_89004f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalcopy',
            index=models.Index(fields=['status', 'book'], name='inventory_p_status_47d155_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['-timestamp'], name='inventory_i_timesta_e236fd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['physical_copy', '-timestamp'], name='inventory_i_physica_a41288_idx'),
        ),
    ]
