"""
Django settings for karunodaya_project project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-k24g%xcakvhqbyzv3q*vj-c29+00qrtcry)-q3216^o%kounvr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Allow all hosts in development for tunnel access
ALLOWED_HOSTS = ['*']

# Trust all origins in development for tunnel/mobile access
CSRF_TRUSTED_ORIGINS = [
    'https://*.github.dev',
    'https://*.ngrok-free.app',
    'https://*.trycloudflare.com',
    'https://*.app.github.dev',
    'http://*.127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    # Django Unfold (must be before admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # For site domain configuration

    # Third-party apps
    'django_htmx',
    'debug_toolbar',

    # Local apps
    'apps.profiles',
    'apps.catalog',
    'apps.inventory',
    'apps.orders',
    'apps.payments',
    'apps.portal',
    'apps.core',  # Enhanced table system
    'apps.feedback',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Third-party middleware
    'django_htmx.middleware.HtmxMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'karunodaya_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'apps.portal.context_processors.reading_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'karunodaya_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL', default=f"postgres://{config('DB_USER', default='karunodaya1')}:{config('DB_PASSWORD', default='1010')}@{config('DB_HOST', default='localhost')}:{config('DB_PORT', default='5432')}/{config('DB_NAME', default='karunodaya')}"),
        conn_max_age=600,
        ssl_require=config('DB_SSL', default=False, cast=bool)
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Allow audio file uploads up to 10MB for fluency check
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='')


# Email Configuration
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Karunodaya <noreply@karunodaya.com>')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@karunodaya.com')
EMAIL_TIMEOUT = 10

# Site Configuration
SITE_ID = 1


# Debug Toolbar Configuration (for development)
INTERNAL_IPS = []


from django.templatetags.static import static

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Karunodaya Admin",
    "SITE_HEADER": "Karunodaya Book Platform",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("images/foundation-logo.png"),
        "dark": lambda request: static("images/foundation-logo.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("images/foundation-logo.png"),
        "dark": lambda request: static("images/foundation-logo.png"),
    },
    "SITE_SYMBOL": "book",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "karunodaya_project.settings.environment_callback",
    "DASHBOARD_CALLBACK": "karunodaya_project.settings.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "255 247 237",
            "100": "255 237 213",
            "200": "254 215 170",
            "300": "253 186 116",
            "400": "251 146 60",
            "500": "249 115 22",  # Standard Orange 500
            "600": "234 88 12",
            "700": "194 65 12",
            "800": "154 52 18",
            "900": "124 45 18",
        },
    },
    "STYLES": [
        lambda request: static("css/admin_custom.css"),
    ],
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "items": [
                    {
                        "title": _("Home"),
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Authentication"),
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Catalog"),
                "items": [
                    {
                        "title": _("Books"),
                        "icon": "book",
                        "link": reverse_lazy("admin:catalog_book_changelist"),
                    },
                    {
                        "title": _("Publishers"),
                        "icon": "business",
                        "link": reverse_lazy("admin:catalog_publisher_changelist"),
                    },
                ],
            },
            {
                "title": _("Inventory"),
                "items": [
                    {
                        "title": _("Inventory Logs"),
                        "icon": "history",
                        "link": reverse_lazy("admin:inventory_inventorylog_changelist"),
                    },
                    {
                        "title": _("Physical Copies"),
                        "icon": "content_copy",
                        "link": reverse_lazy("admin:inventory_physicalcopy_changelist"),
                    },
                ],
            },
            {
                "title": _("Orders"),
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Subscription Cycles"),
                        "icon": "sync",
                        "link": reverse_lazy("admin:orders_subscriptioncycle_changelist"),
                    },
                    {
                        "title": _("Subscription Plans"),
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:orders_subscriptionplan_changelist"),
                    },
                ],
            },
            {
                "title": _("Payments"),
                "items": [
                    {
                        "title": _("Transactions"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:payments_transaction_changelist"),
                    },
                ],
            },
            {
                "title": _("Portal"),
                "items": [
                    {
                        "title": _("Complaints"),
                        "icon": "report_problem",
                        "link": reverse_lazy("admin:portal_complaint_changelist"),
                    },
                    {
                        "title": _("App Feedback"),
                        "icon": "feedback",
                        "link": reverse_lazy("admin:feedback_appfeedback_changelist"),
                    },
                    {
                        "title": _("Cycle Feedback"),
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:feedback_cyclefeedback_changelist"),
                    },
                ],
            },
            {
                "title": _("Profiles"),
                "items": [
                    {
                        "title": _("Children"),
                        "icon": "child_care",
                        "link": reverse_lazy("admin:profiles_child_changelist"),
                    },
                    {
                        "title": _("Parent Profiles"),
                        "icon": "account_box",
                        "link": reverse_lazy("admin:profiles_parentprofile_changelist"),
                    },
                ],
            },
            {
                "title": _("Configuration"),
                "items": [
                    {
                        "title": _("Sites"),
                        "icon": "public",
                        "link": reverse_lazy("admin:sites_site_changelist"),
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """Show environment badge in admin."""
    return ["Development", "warning"] if DEBUG else ["Production", "danger"]


def dashboard_callback(request, context):
    """Customize admin dashboard with stats."""
    from apps.orders.models import Order, SubscriptionCycle
    from apps.inventory.models import PhysicalCopy
    from apps.catalog.models import Book
    from apps.portal.models import Complaint
    from django.db.models import Sum, Q, Count
    from datetime import datetime, timedelta

    # Active Subscriptions
    active_subscriptions = SubscriptionCycle.objects.filter(
        status__in=['ACTIVE', 'OVERDUE']
    ).count()

    overdue_subscriptions = SubscriptionCycle.objects.filter(
        status='OVERDUE'
    ).count()

    # Revenue
    total_revenue = Order.objects.filter(
        status__in=['PAID', 'DISPATCHED', 'DELIVERED']
    ).aggregate(total=Sum('total_amount'))['total'] or 0

    # Monthly revenue
    first_day_of_month = datetime.now().replace(day=1)
    monthly_revenue = Order.objects.filter(
        status__in=['PAID', 'DISPATCHED', 'DELIVERED'],
        created_at__gte=first_day_of_month
    ).aggregate(total=Sum('total_amount'))['total'] or 0

    # Books Out
    books_out = PhysicalCopy.objects.filter(status='ISSUED').count()
    available_copies = PhysicalCopy.objects.filter(status='AVAILABLE').count()

    # Low Inventory
    low_stock_books = Book.objects.annotate(
        available_copies_count=Count(
            'physical_copies',
            filter=Q(physical_copies__status='AVAILABLE')
        )
    ).filter(
        is_subscription_eligible=True,
        available_copies_count__lt=5,
        available_copies_count__gt=0
    )

    low_inventory_count = low_stock_books.count()
    critical_inventory_count = low_stock_books.filter(available_copies_count__lt=2).count()

    # Recent Orders
    recent_orders = Order.objects.select_related('parent__user').order_by('-created_at')[:5]

    # Complaints
    complaints_count = Complaint.objects.count()
    pending_complaints = Complaint.objects.filter(status='PENDING').count()

    # Add to context
    context['stats'] = {
        'active_subscriptions': active_subscriptions,
        'overdue_subscriptions': overdue_subscriptions,
        'total_revenue': total_revenue,
        'monthly_revenue': monthly_revenue,
        'books_out': books_out,
        'available_copies': available_copies,
        'low_inventory_count': low_inventory_count,
        'critical_inventory_count': critical_inventory_count,
        'complaints_count': complaints_count,
        'pending_complaints': pending_complaints,
    }

    context['recent_orders'] = recent_orders
    context['low_stock_books'] = low_stock_books[:5]

    return context
