# Generated by Django 5.0.9 on 2026-01-13 03:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('difficulty_rating', models.CharField(choices=[('BEGINNER', 'Beginner (Ages 3-6)'), ('INTERMEDIATE', 'Intermediate (Ages 7-10)'), ('ADVANCED', 'Advanced (Ages 11-14)')], help_text='Reading difficulty level', max_length=20)),
                ('recommended_grade_min', models.CharField(choices=[('PRE_K', 'Pre-K'), ('KINDERGARTEN', 'Kindergarten'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8')], max_length=20, verbose_name='Minimum Grade')),
                ('recommended_grade_max', models.CharField(choices=[('PRE_K', 'Pre-K'), ('KINDERGARTEN', 'Kindergarten'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8')], max_length=20, verbose_name='Maximum Grade')),
                ('is_subscription_eligible', models.BooleanField(default=True, help_text='Can be included in subscription boxes')),
                ('is_purchase_eligible', models.BooleanField(default=True, help_text='Can be purchased from marketplace')),
                ('stock_count', models.IntegerField(default=0, help_text='Available stock for purchases (not subscription copies)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['difficulty_rating', 'is_subscription_eligible'], name='catalog_boo_difficu_697431_idx'), models.Index(fields=['is_purchase_eligible', 'stock_count'], name='catalog_boo_is_purc_98e54e_idx')],
            },
        ),
    ]
