# Generated by Django 5.1.15 on 2026-03-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='locality_tags',
            field=models.JSONField(blank=True, default=list, help_text='Cultural/regional tags for locality-aware curation e.g. ["Tamil Nadu", "Chennai", "Idli"]'),
        ),
    ]
