# Generated by Django 5.1.15 on 2026-02-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_schedul_7781eb_idx',
            old_name='notif_log_date_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_parent__851d99_idx',
            old_name='notif_log_parent_date_idx',
        ),
    ]
