# Generated by Django 5.1.15 on 2026-02-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notif_log_date_type_idx_notificatio_schedul_7781eb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android APK'), ('ios', 'iOS App'), ('web', 'Web Browser')], default='android', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1159a5_idx'), models.Index(fields=['platform'], name='notificatio_platfor_b2e70c_idx')],
            },
        ),
    ]
